// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.tradedataprovider;

import com.gergo.takacs.tradedataprovider.TradeIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TradeIntegrationTest_Roo_Configurable {
    
    declare @type: TradeIntegrationTest: @Configurable;
    
}
