// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.tradedataprovider;

import com.gergo.takacs.trade.TradeDirection;
import com.gergo.takacs.tradedataprovider.Trade;
import com.gergo.takacs.tradedataprovider.TradeDataOnDemand;
import com.gergo.takacs.tradedataprovider.TradeRepository;
import com.gergo.takacs.tradedataprovider.TradeService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TradeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TradeDataOnDemand: @Component;
    
    private Random TradeDataOnDemand.rnd = new SecureRandom();
    
    private List<Trade> TradeDataOnDemand.data;
    
    @Autowired
    TradeService TradeDataOnDemand.tradeService;
    
    @Autowired
    TradeRepository TradeDataOnDemand.tradeRepository;
    
    public Trade TradeDataOnDemand.getNewTransientTrade(int index) {
        Trade obj = new Trade();
        setCreationTime(obj, index);
        setDirection(obj, index);
        setPrice(obj, index);
        setQuantity(obj, index);
        setStockSymbol(obj, index);
        return obj;
    }
    
    public void TradeDataOnDemand.setCreationTime(Trade obj, int index) {
        Date creationTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationTime(creationTime);
    }
    
    public void TradeDataOnDemand.setDirection(Trade obj, int index) {
        TradeDirection direction = TradeDirection.class.getEnumConstants()[0];
        obj.setDirection(direction);
    }
    
    public void TradeDataOnDemand.setPrice(Trade obj, int index) {
        double price = new Integer(index).doubleValue();
        obj.setPrice(price);
    }
    
    public void TradeDataOnDemand.setQuantity(Trade obj, int index) {
        int quantity = index;
        if (quantity < 1) {
            quantity = 1;
        }
        obj.setQuantity(quantity);
    }
    
    public void TradeDataOnDemand.setStockSymbol(Trade obj, int index) {
        String stockSymbol = "stockSymbol_" + index;
        obj.setStockSymbol(stockSymbol);
    }
    
    public Trade TradeDataOnDemand.getSpecificTrade(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Trade obj = data.get(index);
        Long id = obj.getId();
        return tradeService.findTrade(id);
    }
    
    public Trade TradeDataOnDemand.getRandomTrade() {
        init();
        Trade obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return tradeService.findTrade(id);
    }
    
    public boolean TradeDataOnDemand.modifyTrade(Trade obj) {
        return false;
    }
    
    public void TradeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = tradeService.findTradeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Trade' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Trade>();
        for (int i = 0; i < 10; i++) {
            Trade obj = getNewTransientTrade(i);
            try {
                tradeService.saveTrade(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            tradeRepository.flush();
            data.add(obj);
        }
    }
    
}
