// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.tradedataprovider;

import com.gergo.takacs.tradedataprovider.TradeDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TradeDataOnDemand_Roo_Configurable {
    
    declare @type: TradeDataOnDemand: @Configurable;
    
}
