// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.tradedataprovider;

import com.gergo.takacs.tradedataprovider.TradeDataOnDemand;
import com.gergo.takacs.tradedataprovider.TradeIntegrationTest;
import com.gergo.takacs.tradedataprovider.TradeRepository;
import com.gergo.takacs.tradedataprovider.TradeService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TradeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TradeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TradeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TradeIntegrationTest: @Transactional;
    
    @Autowired
    TradeDataOnDemand TradeIntegrationTest.dod;
    
    @Autowired
    TradeService TradeIntegrationTest.tradeService;
    
    @Autowired
    TradeRepository TradeIntegrationTest.tradeRepository;
    
    @Test
    public void TradeIntegrationTest.testCountAllTrades() {
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", dod.getRandomTrade());
        long count = tradeService.countAllTrades();
        Assert.assertTrue("Counter for 'Trade' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TradeIntegrationTest.testFindTrade() {
        Trade obj = dod.getRandomTrade();
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trade' failed to provide an identifier", id);
        obj = tradeService.findTrade(id);
        Assert.assertNotNull("Find method for 'Trade' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Trade' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TradeIntegrationTest.testFindAllTrades() {
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", dod.getRandomTrade());
        long count = tradeService.countAllTrades();
        Assert.assertTrue("Too expensive to perform a find all test for 'Trade', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Trade> result = tradeService.findAllTrades();
        Assert.assertNotNull("Find all method for 'Trade' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Trade' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TradeIntegrationTest.testFindTradeEntries() {
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", dod.getRandomTrade());
        long count = tradeService.countAllTrades();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Trade> result = tradeService.findTradeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Trade' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Trade' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TradeIntegrationTest.testFlush() {
        Trade obj = dod.getRandomTrade();
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trade' failed to provide an identifier", id);
        obj = tradeService.findTrade(id);
        Assert.assertNotNull("Find method for 'Trade' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTrade(obj);
        Integer currentVersion = obj.getVersion();
        tradeRepository.flush();
        Assert.assertTrue("Version for 'Trade' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TradeIntegrationTest.testUpdateTradeUpdate() {
        Trade obj = dod.getRandomTrade();
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trade' failed to provide an identifier", id);
        obj = tradeService.findTrade(id);
        boolean modified =  dod.modifyTrade(obj);
        Integer currentVersion = obj.getVersion();
        Trade merged = tradeService.updateTrade(obj);
        tradeRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Trade' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TradeIntegrationTest.testSaveTrade() {
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", dod.getRandomTrade());
        Trade obj = dod.getNewTransientTrade(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Trade' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Trade' identifier to be null", obj.getId());
        try {
            tradeService.saveTrade(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        tradeRepository.flush();
        Assert.assertNotNull("Expected 'Trade' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TradeIntegrationTest.testDeleteTrade() {
        Trade obj = dod.getRandomTrade();
        Assert.assertNotNull("Data on demand for 'Trade' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trade' failed to provide an identifier", id);
        obj = tradeService.findTrade(id);
        tradeService.deleteTrade(obj);
        tradeRepository.flush();
        Assert.assertNull("Failed to remove 'Trade' with identifier '" + id + "'", tradeService.findTrade(id));
    }
    
}
