// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.stock.dataprovider;

import com.gergo.takacs.stock.dataprovider.CommonStockEntityIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CommonStockEntityIntegrationTest_Roo_Configurable {
    
    declare @type: CommonStockEntityIntegrationTest: @Configurable;
    
}
