// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.stock.dataprovider;

import com.gergo.takacs.stock.dataprovider.CommonStockEntityDataOnDemand;
import com.gergo.takacs.stock.dataprovider.CommonStockEntityIntegrationTest;
import com.gergo.takacs.stock.dataprovider.PreferredStockEntityService;
import com.gergo.takacs.stock.dataprovider.PreferredStockRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CommonStockEntityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CommonStockEntityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CommonStockEntityIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CommonStockEntityIntegrationTest: @Transactional;
    
    @Autowired
    CommonStockEntityDataOnDemand CommonStockEntityIntegrationTest.dod;
    
    @Autowired
    PreferredStockEntityService CommonStockEntityIntegrationTest.preferredStockEntityService;
    
    @Autowired
    PreferredStockRepository CommonStockEntityIntegrationTest.preferredStockRepository;
    
    @Test
    public void CommonStockEntityIntegrationTest.testCountAllCommonStockEntitys() {
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", dod.getRandomCommonStockEntity());
        long count = preferredStockEntityService.countAllCommonStockEntitys();
        Assert.assertTrue("Counter for 'CommonStockEntity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CommonStockEntityIntegrationTest.testFindCommonStockEntity() {
        CommonStockEntity obj = dod.getRandomCommonStockEntity();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to provide an identifier", id);
        obj = preferredStockEntityService.findCommonStockEntity(id);
        Assert.assertNotNull("Find method for 'CommonStockEntity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CommonStockEntity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CommonStockEntityIntegrationTest.testFindAllCommonStockEntitys() {
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", dod.getRandomCommonStockEntity());
        long count = preferredStockEntityService.countAllCommonStockEntitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'CommonStockEntity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CommonStockEntity> result = preferredStockEntityService.findAllCommonStockEntitys();
        Assert.assertNotNull("Find all method for 'CommonStockEntity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CommonStockEntity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CommonStockEntityIntegrationTest.testFindCommonStockEntityEntries() {
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", dod.getRandomCommonStockEntity());
        long count = preferredStockEntityService.countAllCommonStockEntitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CommonStockEntity> result = preferredStockEntityService.findCommonStockEntityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CommonStockEntity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CommonStockEntity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CommonStockEntityIntegrationTest.testFlush() {
        CommonStockEntity obj = dod.getRandomCommonStockEntity();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to provide an identifier", id);
        obj = preferredStockEntityService.findCommonStockEntity(id);
        Assert.assertNotNull("Find method for 'CommonStockEntity' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCommonStockEntity(obj);
        Integer currentVersion = obj.getVersion();
        preferredStockRepository.flush();
        Assert.assertTrue("Version for 'CommonStockEntity' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommonStockEntityIntegrationTest.testUpdateCommonStockEntityUpdate() {
        CommonStockEntity obj = dod.getRandomCommonStockEntity();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to provide an identifier", id);
        obj = preferredStockEntityService.findCommonStockEntity(id);
        boolean modified =  dod.modifyCommonStockEntity(obj);
        Integer currentVersion = obj.getVersion();
        CommonStockEntity merged = (CommonStockEntity)preferredStockEntityService.updateCommonStockEntity(obj);
        preferredStockRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CommonStockEntity' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommonStockEntityIntegrationTest.testSaveCommonStockEntity() {
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", dod.getRandomCommonStockEntity());
        CommonStockEntity obj = dod.getNewTransientCommonStockEntity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CommonStockEntity' identifier to be null", obj.getId());
        try {
            preferredStockEntityService.saveCommonStockEntity(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        preferredStockRepository.flush();
        Assert.assertNotNull("Expected 'CommonStockEntity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CommonStockEntityIntegrationTest.testDeleteCommonStockEntity() {
        CommonStockEntity obj = dod.getRandomCommonStockEntity();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CommonStockEntity' failed to provide an identifier", id);
        obj = preferredStockEntityService.findCommonStockEntity(id);
        preferredStockEntityService.deleteCommonStockEntity(obj);
        preferredStockRepository.flush();
        Assert.assertNull("Failed to remove 'CommonStockEntity' with identifier '" + id + "'", preferredStockEntityService.findCommonStockEntity(id));
    }
    
}
