// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.trade.dataprovider;

import com.gergo.takacs.trade.dataprovider.TradeEntityDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TradeEntityDataOnDemand_Roo_Configurable {
    
    declare @type: TradeEntityDataOnDemand: @Configurable;
    
}
