// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.stock.dataprovider;

import com.gergo.takacs.stock.dataprovider.CommonStockEntity;
import javax.persistence.Entity;

privileged aspect CommonStockEntity_Roo_Jpa_Entity {
    
    declare @type: CommonStockEntity: @Entity;
    
}
