// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gergo.takacs.stock.dataprovider;

import com.gergo.takacs.stock.dataprovider.PreferredStockEntity;
import javax.persistence.Entity;

privileged aspect PreferredStockEntity_Roo_Jpa_Entity {
    
    declare @type: PreferredStockEntity: @Entity;
    
}
